name: 诺艾尔

on:
  workflow_dispatch:

jobs:
  spider:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Getting Img Info
      env:
        SQLHOST: ${{ secrets.SQLHOST }}
        SQLUSER: ${{ secrets.SQLUSER }}
        SQLPSD: ${{ secrets.SQLPSD }}
        SQLDB: ${{ secrets.SQLDB }}
        COOKIE: ${{ secrets.COOKIE }}
      run: |
        pip install requests
        pip install lxml
        pip install pymysql
        pwd
        python index.py 诺艾尔
